#!/bin/bash

# CREATE BACKUP PROCEDURE
# 1. Remove prior backup directories
# 2. Copy the data from mounted snapshots to the backup directory
# 3. Unmount the snapshot
# 4. Remove the snapshot

BASEBACKUPDIR=/voyagerbackup

MNTTDIR=${BASEBACKUPDIR}/mnt

# Volume Group name for all ExLibris application storage LVM devices
APP_VGNAME=vg_voyager

# Logical Volume Group names contained within $APP_VGNAME
# Expect the following: lv_m1 lv_oracle lv_oradata
APP_LVNAME=`lvs | grep ${APP_VGNAME} | awk '{ print $1 }' | egrep -v "backup|snap"`

TODAY=`date +%Y%m%d`

for LV in ${APP_LVNAME} ; do
  BACKUPDIR=${BASEBACKUPDIR}/`echo ${LV} | sed s/lv_//g`

  # Find and remove any old/lingering back-up directories in ${BACKUPDIR}
  # These should have already been captured by NetBackup
  REMOVEDIR=`find ${BACKUPDIR}/* -maxdepth 0 -type d -mmin +1440 2> /dev/null`
  if [ -n ${REMOVEDIR} ] ; then
    for DIR in ${REMOVEDIR} ; do
      rm -rf ${DIR}
    done
  fi

  rsync -r -l -g -o -p -t -H -q --links --inplace \
    ${MNTTDIR}/${LV}_snap_${TODAY}/ ${BACKUPDIR}/${LV}_snap_${TODAY} > /dev/null 2>&1
  if [ $? -ne 0 ] ; then
    echo "Copy of ${LV}_snap_${TODAY} snapshot to ${BACKUPDIR}/${LV}_snap_${TODAY} failed. Backup process halting."
    exit 1
  fi

  umount ${MNTTDIR}/${LV}_snap_${TODAY}
  rm -rf ${MNTTDIR}/${LV}_snap_${TODAY}
  lvremove -f /dev/${APP_VGNAME}/${LV}_snap_${TODAY} > /dev/null 2>&1
  if [ $? -ne 0 ] ; then
    echo "WARNING: Unable to remove snapshot ${LV}_snap_${TODAY}"
  fi
done
