#!/bin/bash

# CREATE BACKUP PROCEDURE
# 1. Remove prior backup directories
# 2. Copy the data from mounted snapshots to the backup directory
# 3. Unmount the snapshot
# 4. Remove the snapshot

BASEBACKUPDIR=/voyagerbackup

MNTTDIR=${BASEBACKUPDIR}/mnt

# Volume Group name for all ExLibris application storage LVM devices
APP_VGNAME=vg_voyager

# Logical Volume Group names contained within $APP_VGNAME
# Expect the following: lv_m1 lv_oracle lv_oradata
APP_LVNAME=`lvs | grep ${APP_VGNAME} | awk '{ print $1 }' | egrep -v "backup|snap"`

TODAY=`date +%Y%m%d`
DAYSAGO=`date -d 'now - 1 days' "+%Y%m%d"`

for LV in ${APP_LVNAME} ; do
  # Example BACKUPDIR: /voyagerbackup/m1
  BACKUPDIR=${BASEBACKUPDIR}/`echo ${LV} | sed s/lv_//g`

  # Remove old back-up directories in ${BACKUPDIR}
  # Keep only yesterday and today's backups
  # All previous backups have already been captured by NetBackup
  DIRLIST=`find ${BACKUPDIR}/* -maxdepth 0 -type d -name "lv_*_snap_????????" -printf "%f\n"`
  for DIR in ${DIRLIST} ; do
    # Grab just the date suffix (YYYYMMDD) from the backup dir name lv_*_snap_YYYYMMDD
    DATE=`echo ${DIR} | awk -F "_" '{ print $4 }'`
    if [ $(( ${DATE} - ${DAYSAGO} )) -lt 0 ] ; then
      rm -rf ${BACKUPDIR}/${DIR}
    fi
  done

  rsync -r -l -g -o -p -t -H -q --links --inplace \
    ${MNTTDIR}/${LV}_snap_${TODAY}/ ${BACKUPDIR}/${LV}_snap_${TODAY} > /dev/null 2>&1
  if [ $? -ne 0 ] ; then
    echo "Copy of ${LV}_snap_${TODAY} snapshot to ${BACKUPDIR}/${LV}_snap_${TODAY} failed. Backup process halting." | mail -s "Voyager Backup ERROR: Copy of snapshot failed" lib_devsupport@library.ucla.edu
    exit 1
  fi

  umount ${MNTTDIR}/${LV}_snap_${TODAY}
  rm -rf ${MNTTDIR}/${LV}_snap_${TODAY}
  lvremove -f /dev/${APP_VGNAME}/${LV}_snap_${TODAY} > /dev/null 2>&1
  if [ $? -ne 0 ] ; then
    echo "WARNING: Unable to remove snapshot ${LV}_snap_${TODAY}" | mail -s "Voyager Backup WARNING: Unable to remove snapshot" lib_devsupport@library.ucla.edu
  fi
done
