#!/bin/sh

# Set OCLC EDX FTP password to uclaYYMM for given account
# where YYMM = current year and month.

if [ -n "$1" ]; then
  USER=$1
else
  echo "Usage: $0 edx_account (tclu1, tzas1 etc.)"
  exit 1
fi

# Get voyager environment, for vars and for cron
. `echo $HOME | sed "s/$LOGNAME/voyager/"`/.profile.local

OLDPWD=`${VGER_SCRIPT}/get_value.pl ${VGER_CONFIG}/oclc_credentials ${USER}`
NEWPWD=ucla`date "+%y%m"`

if [ -z "${OLDPWD}" ]; then
  echo "Could not get old password for ${USER} - exiting"
  exit 1
fi

# Change password by sending old/new/new
# 1:  echo "user ${USER} ${OLDPWD}"
# 2:  echo "user ${USER} ${OLDPWD}/${NEWPWD}/${NEWPWD}"
(
  echo "user ${USER} ${OLDPWD}/${NEWPWD}/${NEWPWD}"
  echo "quit"
) | ftp -i -n -v edx.oclc.org

