#!/bin/sh
# Rebuild tables used for cataloging Analyzer reports, which depend on the subfield db
# Takes about 90 minutes to run

# Get voyager environment, for vars and for cron
. `echo $HOME | sed "s/$LOGNAME/voyager/"`/.profile.local

SQL=/m1/voyager/ucladb/local/cat/reports/build_cat_report_tables
${VGER_SCRIPT}/vger_sqlplus_run vger_report ${SQL}

#Include logged output in script output, for email
cat ${SQL}.out

