#!/bin/sh

# Env vars for Oracle and Voyager, available for userids other than
#   oracle
#   voyager
# Three files, three names
#   vger_getenv		both Oracle and Voyager
#   vger_oraenv		Oracle only
#   vger_voyenv		Voyager only

# Voyager only

# 2013-01-02 gloriar: /m1/voyager/*db/ini/voyager.env used to set RELEASE, now it sets VERSION
# For example
#   export VERSION=2007.2.0
#   export VERSION=2008.2.0
# Assume the highest version number is accurate
# Other files that set VERSION
#   /m1/voyager/*db/install/tokens.cfg
VERSION=`grep -h VERSION= /m1/voyager/*db/ini/voyager.env | sort -u | tail -1 | cut -f2 -d'='`

# 2013-01-02 gloriar: we may still use RELEASE somewhere
RELEASE=$VERSION

VGER_BASE=/m1/voyager				export VGER_BASE
VGER_BIN=$VGER_BASE/bin/$RELEASE		export VGER_BIN
# 2006-08-24 akohler: added VGER_UTIL
VGER_UTIL=$VGER_BASE/utility/$RELEASE		export VGER_UTIL

# $VGER_BASE/lib/$RELEASE was needed for libicuuc.so.24, among others
if [ -z "$LD_LIBRARY_PATH" ]
then
    LD_LIBRARY_PATH=$VGER_BASE/lib/$RELEASE
else
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VGER_BASE/lib/$RELEASE
fi
export LD_LIBRARY_PATH
