#!/bin/sh
# Loads data into vger_subfields.ucladb_bib_subfield_del_948
# to support cataloging statistics reports.

if [ -n "$1" ]; then
  DELFILE=$1
else
  echo "Usage: $0 marcfile"
  exit 1
fi

BIN=/opt/local/bin

# For cron
. ${BIN}/vger_getenv

# Everything happens here
DIR=/m1/voyager/ucladb/local/cat
cd ${DIR}

${DIR}/get_marc_by_tag.pl ${DELFILE} 948 > 948.mrc
# Generate tab-delimited file of MARC data, one row per subfield
${BIN}/build_marc_subfield_file 948.mrc 948.sub
# Get just the rows of 948.sub where the 5th column contains certain values.
# Switched from awk to perl due to line-length limitations in awk.
cat 948.sub | perl -anl -F'\t' -e 'print $_ if ($F[4] =~ /LDR|008|035a|040a|049a|948/);' > 948_filtered.sub
# Load the filtered data into database
${BIN}/vger_sqlldr_load vger_subfields 948_filtered.sub deleted_subfields.ctl

# Cleanup
rm -f 948.mrc 948*.sub

