#!/bin/sh

# Get voyager environment, for vars and for cron
. `echo $HOME | sed "s/$LOGNAME/voyager/"`/.profile.local

# Meant to be called by userid oracle, with full login environment
sqlplus -S '/ as sysdba' @${VGER_SCRIPT}/vger_check_oracle_freespace.sql
