#!/bin/sh

# Get voyager environment, for vars and for cron
. `echo $HOME | sed "s/$LOGNAME/voyager/"`/.profile.local

JAVA=${BIN}/java
JAVADIR=${VGER_JAVA}
CLASSPATH=${JAVADIR}/reconciler.jar:${JAVADIR}/commons.jar:${JAVADIR}/ojdbc7.jar:${JAVADIR}/spring.jar:${JAVADIR}/commons-lang-2.6.jar:${JAVADIR}/log4j-1.2.15.jar
PROPERTIES_FILE=${JAVADIR}/reconcile.props

${JAVA} -classpath ${CLASSPATH} edu.ucla.library.libservices.webservices.invoices.reconcile.main.Reconciler ${PROPERTIES_FILE}

