#!/bin/sh
# Rebuilds archive of cataloging statistics
#
# Created: 20071205 akohler

# Include environment for cron
BIN=/usr/local/bin
. ${BIN}/vger_getenv

DIR=/m1/voyager/ucladb/local/cat
#${BIN}/vger_sqlplus_run vger_report ${DIR}/create_948_archive
${BIN}/vger_sqlplus_run vger_report ${DIR}/update_948_archive
if [ -s ${DIR}/update_948_archive.out ]; then
  cat ${DIR}/update_948_archive.out
fi

