#!/bin/bash

# VOYAGER BACKUP PROCEDURE
# 1. Remove any prior backup directories
# 2. Create LVM snapshots of each of the Voyager volumes
# 3. Mount the snapshots
# 4. Copy the data from mounted snapshot to the backup directory
# 5. Unmount the snapshot
# 6. Remove the snapshot
# 7. NetBackup will perform a full back-up of the copied snapshot data

BASEBACKUPDIR=/backup

MNTTDIR=${BASEBACKUPDIR}/mnt

# Volume Group name for all Voyager storage LVM devices
VGER_VGNAME=vg_voyager

# Logical Volume Group names contained within $VGER_VGNAME
# Expect the following: lv_m1 lv_oracle lv_oradata
VGER_LVNAME=`lvs | grep ${VGER_VGNAME} | awk '{ print $1 }' | grep -v backup`

# Snapshot Logical Volume Size
# This is not the size of the snapshot, but rather the amount of delta that
# is allowed to accumlate during the life time of the snapshot volume.
# For example, if LVSIZE=2G, then 2GB worth of filesystem changes can be stored
LVSIZE=10G

TODAY=`date +%Y%m%d`

for LV in ${VGER_LVNAME} ; do
  BACKUPDIR=${BASEBACKUPDIR}/`echo ${LV} | sed s/lv_//g`

  REMOVEDIR=`find ${BACKUPDIR}/* -maxdepth 0 -type d -mmin +1440`

  if [ -n ${REMOVEDIR} ] ; then
    for DIR in ${REMOVEDIR} ; do
      rm -rf ${DIR}
    done
  fi

  lvcreate -L${LVSIZE} -s -n ${LV}_snap_${TODAY} /dev/${VGER_VGNAME}/${LV} > /dev/null 2>&1
  mkdir -p ${BACKUPDIR}/${LV}_snap_${TODAY}
  mount /dev/${VGER_VGNAME}/${LV}_snap_${TODAY} ${MNTTDIR}

  rsync -r -l -g -o -p -t -H      \
    --safe-links --temp-dir=/tmp  \
    ${MNTTDIR}/ ${BACKUPDIR}/${LV}_snap_${TODAY} > /dev/null 2>&1

  umount ${MNTTDIR}
  lvremove -f /dev/${VGER_VGNAME}/${LV}_snap_${TODAY} > /dev/null 2>&1
done

