#!/bin/sh
# Retrieves and loads Harrassowitz records (brief bib/order records)
# Intended to be run daily, to process previous day's file if present

# Get voyager environment, for vars and for cron
. `echo $HOME | sed "s/$LOGNAME/voyager/"`/.profile.local

# Mandatory parameter: date in YYYYMMDD
if [ -n "$1" ]; then
  DATE=$1
else
  # No parameter, use yesterday's date
  DELTA=-1
  . ${VGER_SCRIPT}/vger_ymd_delta
  DATE=${YEAR}${MONTH}${DAY}
fi

# The magic happens here
DIR=/m1/voyager/ucladb/local/eod/harrassowitz
cd ${DIR}

# HAR files look like this:
# 20110203061639.18.orders.marc21.abc (OBSOLETE)
# 20151202062203.18.ord.mrc (2015-11 and later)
# Get all files for given YYYYMMDD
# Multiple HAR accounts - only one has these files - hardcoded for now
USER=uclalib3
PASSWORD=`${VGER_SCRIPT}/get_value.pl ${VGER_CONFIG}/harrassowitz_credentials ${USER}`
(
  echo "user ${USER} ${PASSWORD}"
  echo "bin"
  echo "mget ${DATE}*.mrc"
  echo "quit"
) | ftp -n -i -v ftp.harrassowitz.de

# Now process any files
for LOADFILE in *.mrc; do
  if [ -f ${LOADFILE} ]; then
    BASEFILE=`basename ${LOADFILE} .mrc`

    # Load the file into Voyager
    echo "Loading ${LOADFILE}..."
    ${VGER_SCRIPT}/vger_bulkimport_file ${LOADFILE} ucladb HAR promptcat

	#Reminder: LOADFILE = BASEFILE.mrc - both are used below

	# Rename log file
	LOGFILE=${BASEFILE}.log
	mv log.imp.${LOADFILE}.bulk ${LOGFILE}

    # Rename file of rejected records
    if [ -f discard.imp.${LOADFILE}.bulk ]; then
      mv discard.imp.${LOADFILE}.bulk ${BASEFILE}.rej.mrc
    fi

  fi # -f ${LOADFILE}
done # ${LOADFILE}

# Email relevant log info from all of the resulting logs to specific users
grep -h "Purchase Order Number" *.log | grep -v "check log" | mailx -s "HAR loaded ${LOADFILE}" \
  mono-acq@library.ucla.edu lit-libweb@library.ucla.edu

# Move files into the archive
mv ${BASEFILE}* ${DIR}/archive

# Remove archived files older than 180 days
find ${DIR}/archive -type f -mtime +180 -exec rm {} \;

