#!/bin/sh

# Run all daily Voyager-related jobs which need to run together.
# Must run as root, for backup; uses su to run other scripts as
# voyager or oracle.

# Get voyager environment, for vars and for cron
. /home/voyager/.profile.local

echo `date`: Shut down apache, voyager and oracle
/etc/init.d/httpd2 stop
/etc/init.d/voyager stop
/etc/init.d/dbora stop

echo `date`: Starting vger_snap_backup
${VGER_SCRIPT}/vger_snap_backup
echo `date`: Finished vger_snap_backup

echo `date`: Start oracle, voyager and apache
/etc/init.d/dbora start
/etc/init.d/voyager start
/etc/init.d/httpd2 start

echo `date`: Running Acquisitions jobs...
su - voyager -c "${VGER_SCRIPT}/vger_acqjobs"

echo `date`: Running Circulation jobs...
su - voyager -c "${VGER_SCRIPT}/vger_circjobs"

echo `date`: All done

