#!/bin/sh
# Must be run as oracle or other user in dba group
#
# Revisions:
# - 20071211 akohler: changed GRANTS from n to y

# For ORACLE_HOME and other environment
. /usr/local/bin/vger_oraenv

# For running SQL commands
SQLDBA="${ORACLE_HOME}/bin/sqlplus -S /nolog"

# Mandatory parameters
if [ -n "$1" ]; then
  TABLESPACES=$1
else
  echo "Usage: $0 tablespace(s) (single tablespace, or quoted space-separated list of tablespaces)"
  exit 1
fi

for TABLESPACE in ${TABLESPACES}; do
  # Tablespace into read only mode
  echo "Setting tablespace ${TABLESPACE} read only"
  ${SQLDBA} << EOD
  connect / as sysdba
  alter tablespace ${TABLESPACE} read only;
EOD

  # Create Oracle export parameter file
  PARFILE=/tmp/${TABLESPACE}.par.$$
  cat << EOD > ${PARFILE}
  TRANSPORT_TABLESPACE=y
  TABLESPACES=${TABLESPACE}
  TRIGGERS=y
  CONSTRAINTS=y
  GRANTS=n
  FILE=${TABLESPACE}.dmp
EOD

  echo "Exporting tablespace info for ${TABLESPACE}"
  ${ORACLE_HOME}/bin/exp \'/ as sysdba\' parfile=${PARFILE} > ${HOME}/${TABLESPACE}_export.log 2>&1

  # Tablespace into read write mode
  # Handled in vger_tablespace_readwrite, after db files are copied during backup

  # Clean up
  rm ${PARFILE}
done
