#!/bin/sh

############################################################
# Voyager Circulation Stats Export, called from 
# ${VGER_SCRIPT}/vger_circjobs.
#
# This script exports and combines circulation data from 
# Voyager. The files are meant to be imported to the 
# Public Service Stats database.
############################################################

# Get voyager environment, for vars and for cron
. `echo $HOME | sed "s/$LOGNAME/voyager/"`/.profile.local

# Each Voyager database has its own directory
# Voyager and Oracle must be up
case `hostname` in
eliot|wells )
    SERVER=prod                 # production server

    # Run jobs for ucladb, but not for any other database
    # ${VGER_SCRIPT}/vger_daily will take care of rotating logs
    DIR=${VGER_BASE}/ucladb
    ;;
butler|collins )
    SERVER=test                 # test server

    echo "$0: this script can run only on the production server"
    exit 1
    ;;
* )
    echo "$0: this script can run only on a Voyager server"
    exit 1
    ;;
esac

# Any files created should be accessible to the group.
umask 007

CIRCDIR=${DIR}/local/circ

. ${VGER_SCRIPT}/vger_ymd

STARTDATE=${LAST_YYYYMM}01
ENDDATE=${THIS_YYYYMM}01

QUERY_TYPES="charges discharges fees lost overdue overdue_recall recall renewals"
SIMPLE_TYPES="charges discharges overdue renewals"
MERGE_TYPES="fees lost overdue_recall recall"
FILE_TYPES="charges discharges overdue renewals cct"

for TYPE in ${QUERY_TYPES}; do 
  ${VGER_SCRIPT}/vger_sqlplus_run vger_support ${CIRCDIR}/monthly_${TYPE} ${STARTDATE} ${ENDDATE}
done

for TYPE in ${SIMPLE_TYPES}; do
  mv ${CIRCDIR}/monthly_${TYPE}.out ${CIRCDIR}/${TYPE}_${LAST_YYYYMM}.txt
done

for TYPE in ${MERGE_TYPES}; do
  cat ${CIRCDIR}/monthly_${TYPE}.out >> ${CIRCDIR}/cct_${LAST_YYYYMM}.txt
  rm ${CIRCDIR}/monthly_${TYPE}.out
done

# 20090727 added logic to clear out old output files; keep 3 months of files for debug needs drickard
for TYPE in ${FILE_TYPES}; do
  find ${CIRCDIR} -type f -name "${TYPE}_*.txt" -mtime +90 -exec rm {} \;
done





