#!/bin/ksh

# Get voyager environment, for vars and for cron
. `echo $HOME | sed "s/$LOGNAME/voyager/"`/.profile.local

DIR=${VGER_BASE}/ucladb

# Requires day count, provided via $1
if [ -z "$1" ]; then
  echo "Usage: $0 number-of-days"
  exit 1
else
  DAYS=$1
fi

CIRCDIR=${DIR}/local/circ

${VGER_SCRIPT}/vger_sqlplus_run ucladb ${CIRCDIR}/clear_circ_history ${DAYS}


