#!/bin/sh

# Get voyager environment, for vars and for cron
. `echo $HOME | sed "s/$LOGNAME/voyager/"`/.profile.local

# Get ucladb USERPASS credentials, which have necessary rights.
. /m1/voyager/ucladb/ini/voyager.env

sqlplus -S ${USERPASS} @${VGER_SCRIPT}/vger_check_oracle_freespace.sql
