#!/bin/sh
# Create ZASSP (SRLF shared print) OCLC LHRs

# Get voyager environment, for vars and for cron
. `echo $HOME | sed "s/$LOGNAME/voyager/"`/.profile.local

# Everything happens here
LHR=/m1/voyager/ucladb/local/lhr/zassp
cd ${LHR}

# Variables
BASE=${LHR}/zassp_lhr_serials
SQLFILE=${BASE}.sql
DATAFILE=${SQLFILE}.out
MFHDFILE=${BASE}.mfhds

# Use date if provided, else default to last Monday
# LASTDATE = last date records were edited, in YYYYMMDD
if [ -n "$1" ]; then
  LASTDATE=$1
  # Allow full extract of all records by using date prior to Voyager migration
  if [ "$LASTDATE" = "ALL" ]; then
    LASTDATE=20000101
  fi
else
  # Calculate Monday of previous week (at least 7 days ago)
  case `date "+%w"` in          # 0..6 for Sun..Sat
    0 ) DELTA=-13;;
    1 ) DELTA=-7;;
    2 ) DELTA=-8;;
    3 ) DELTA=-9;;
    4 ) DELTA=-10;;
    5 ) DELTA=-11;;
    6 ) DELTA=-12;;
  esac
  # Set YEAR, MONTH, DAY based on DELTA
  # Clear out the commandline parms, else they get sent to vger_ymd_delta
  while [ ! -z "$1" ]; do
    shift
  done

  . ${VGER_SCRIPT}/vger_ymd_delta
  LASTDATE=${YEAR}${MONTH}${DAY}
fi

echo "Extracting LHRs for records updated on/after ${LASTDATE}..."

# Run query to get necessary data
${VGER_SCRIPT}/vger_sqlplus_run ucla_preaddb ${SQLFILE} ${LASTDATE}

# Exit if no data from query
if [ ! -s ${DATAFILE} ]; then
  echo "ERROR: no data in ${DATAFILE} from query - exiting"
  exit 1
fi

# Extract Voyager holdings records, using the list of ids
/m1/voyager/ucladb/sbin/Pmarcexport \
  -rH \
  -mM \
  -t${DATAFILE} \
  -o${MFHDFILE}

# Create OCLC LHRs from the extracted Voyager holdings records
# Results are in zassp_lhrs.mrc, name set by make_zassp_lhrs.pl
${LHR}/make_zassp_lhrs.pl ${DATAFILE} ${MFHDFILE}

# Stats
${BIN}/marcsplit -c zassp_lhrs.mrc

# Combine LHR files into file named for OCLC and generate LABEL file(s)
PROJECT=P014206
YYMMDD=`date "+%y%m%d"`
mv zassp_lhrs.mrc DATA.D${YYMMDD}
${VGER_SCRIPT}/vger_make_oclc_label_files ${PROJECT} ZASSP

# FTP the files to OCLC
USER=tzassp1
PWD=`${VGER_SCRIPT}/get_value.pl ${VGER_CONFIG}/oclc_credentials ${USER}`
(
  echo "user ${USER} ${PWD}"
  echo "cd 'edx.ebsb.zassp.ftp'"
  echo "bin"
  echo "mput DATA*"
  echo "mput LABEL*"
  echo "dir"
  echo "quit"
) | ftp -i -n -v edx.oclc.org

# Cleanup
mv ${LHR}/DATA* ${LHR}/LABEL* ${LHR}/archive/
rm ${DATAFILE} ${MFHDFILE}


