#!/bin/sh

# After a Voyager upgrade, run this to rebuild "vanilla" OPAC
# Caveats:
# - Written and tested on butler only
# - Assumes XXXDB contains upgraded template files

VOYAGER=/m1/voyager
VANILLA=${VOYAGER}/ucla_vandb
UCLA=${VOYAGER}/ucladb
XXXDB=/m1/incoming/FULL/xxxdb

# Check for XXXDB
if [ ! -d ${XXXDB} ]; then
  echo "Error: ${XXXDB} is missing - exiting"
  exit 1
fi

# Remove old vanilla db
rm -rf ${VANILLA}

# Create new empty directory
mkdir ${VANILLA}

# Copy the relevant directories from XXXDB
DIRLIST="etc ini webvoyage"
for DIR in ${DIRLIST}; do
  cp -pR ${XXXDB}/${DIR} ${VANILLA}
  # Change xxxdb placeholder to ucla_vandb in relevant files
  OLDDB=xxxdb
  NEWDB=ucla_vandb
  for FILE in `find ${VANILLA}/${DIR} -type f -exec grep -l ${OLDDB} {} \;`; do
    perl -p -i -e 's/${OLDDB}/${NEWDB}/g' ${FILE}
  done # for FILE
done # for DIR

# Create symlinks from ucladb to vanilla for the other directories
DIRLIST="archive data dmp dump edi local log mfhd.data rpt sbin tmp tomcat webadmin"
for DIR in ${DIRLIST}; do
  ln -s ${UCLA}/${DIR} ${VANILLA}/${DIR}
done

# Copy ucla-configured files
FILES="voyager.env voyager.ini"
for FILE in ${FILES}; do
  cp -p ${UCLA}/ini/${FILE} ${VANILLA}/ini
done


