#!/bin/sh
# Extract SRLF (ZAS) records for OCLC to process; OCLC returns cross-references which
# later get loaded into Voyager.
# WARNING: Don't run this the same day as vger_make_zas_lhrs, as they both upload to same directory
#   on OCLC's FTP site, with (required) same file names based on date.

# Get voyager environment, for vars and for cron
. `echo $HOME | sed "s/$LOGNAME/voyager/"`/.profile.local

# Get start/end dates for selecting records
# Use provided dates, or default to previous Monday thru previous Sunday
# Dates are YYYYMMDD
if [ -n "$2" ]; then
  START_DATE=$1
  END_DATE=$2
else
  # Calculate END_DATE = previous Sunday
  case `date "+%w"` in          # 0..6 for Sun..Sat
    0 ) DELTA=-7;;		# Previous Sunday, not today
    1 ) DELTA=-1;;
    2 ) DELTA=-2;;
    3 ) DELTA=-3;;
    4 ) DELTA=-4;;
    5 ) DELTA=-5;;
    6 ) DELTA=-6;;
  esac
  # Set YEAR, MONTH, DAY based on DELTA
  # Clear out the commandline parms, else they get sent to vger_ymd_delta
  while [ -n "$1" ]; do
    shift
  done

  . ${VGER_SCRIPT}/vger_ymd_delta
  END_DATE=${YEAR}${MONTH}${DAY}
  # Go back another 6 days (to Monday before previous Sunday)
  DELTA=-6
  # Must use "set" command to assign $1 $2 $3 for vger_ymd_delta
  set $YEAR $MONTH $DAY; . ${VGER_SCRIPT}/vger_ymd_delta
  START_DATE=${YEAR}${MONTH}${DAY}
fi

# Everything happens here
DIR=/m1/voyager/ucladb/local/reclamation/zas
cd ${DIR}

DB=${VGER_BASE}/ucladb
DATE=`date "+%y%m%d"` #YYMMDD
SYMBOL=ZAS

for SCRIPT in zas_extract_oclc zas_extract_no_oclc; do
  case ${SCRIPT} in
    zas_extract_oclc ) COLLECTION_ID=1034796;;
	zas_extract_no_oclc ) COLLECTION_ID=1013211;;
  esac

  # Get the full list of ids from database
  ${VGER_SCRIPT}/vger_sqlplus_run vger_report ${SCRIPT} ${START_DATE} ${END_DATE}
  LIST=${SCRIPT}.out

  OCLCFILE=${COLLECTION_ID}.${SYMBOL}.${DATE}.mrc
  ${DB}/sbin/Pmarcexport -o${OCLCFILE} -rB -mM -t${LIST} -q
  rm ${LIST}

  # FTP the files to OCLC
  USER=fx_zas
  PASSWORD=`${VGER_SCRIPT}/get_value.pl ${VGER_CONFIG}/oclc_credentials ${USER}`
  (
    echo "user ${USER} ${PASSWORD}"
    echo "cd /metacoll/in/bib"
    echo "bin"
    echo "put ${OCLCFILE}"
    echo "dir"
    echo "quit"
  ) | ftp -i -n -v filex-m1.oclc.org

  # Clean up
  mv ${OCLCFILE} ${DIR}/archive

done
