#!/bin/sh
# Rebuilds archive of cataloging statistics
#
# Created: 20071205 akohler

# Get voyager environment, for vars and for cron
. `echo $HOME | sed "s/$LOGNAME/voyager/"`/.profile.local

DIR=/m1/voyager/ucladb/local/cat
#${VGER_SCRIPT}/vger_sqlplus_run vger_report ${DIR}/create_948_archive
${VGER_SCRIPT}/vger_sqlplus_run vger_report ${DIR}/update_948_archive
if [ -s ${DIR}/update_948_archive.out ]; then
  cat ${DIR}/update_948_archive.out
fi

