#!/bin/sh

# Manages EDI invoice files from various vendors, for use by Voyager acq client
# Retrieves files, puts them in vendor-specific directories, renames as needed
# Manages links between original files and those in central directory
# Hides old files from Acq client
# Must be run by voyager
# Revisions:
#   20080124 akohler: clean up old code, update comments
#   20080519 akohler: added timeout (-T 120) to ftp command
#   20100504 akohler: added filespec to ftp config 

# Optional commandline parameter: code for one vendor; otherwise will process all vendors
if [ "$1" ]; then
  REQVENDOR=$1
fi

EDI=/m1/voyager/ucladb/edi
CONFIG=${EDI}/config
INCOMING=${EDI}/incoming
TEMP=${INCOMING}/temp

# Read file and process each line
# Connection info in this file instead of .netrc
# because .netrc can't handle paths (without macros) or multiple accounts per machine
cat ${CONFIG}/edi_invoice_sources.lst | \
  while read LINE; do
    # Skip comments
    FIRSTCHAR=`echo ${LINE} | cut -c1`
    if [ "${FIRSTCHAR}" = "#" ]; then
      continue 		# back to top of while read LINE
    fi

    # Chop data lines into fields
    VENDOR=`echo ${LINE} | cut -d, -f1`
    MACHINE=`echo ${LINE} | cut -d, -f2`
    FILEDIR=`echo ${LINE} | cut -d, -f3`
    FILESPEC=`echo ${LINE} | cut -d, -f4`
    USER=`echo ${LINE} | cut -d, -f5`
    PASSWORD=`echo ${LINE} | cut -d, -f6`

    # Retrieve and process EDI files if:
    #  a) input parameter wasn't set, or
    #  b) input parameter is same as vendor in current iteration of loop
    if [ ! ${REQVENDOR} -o ${REQVENDOR} = ${VENDOR} ]; then

      cd ${INCOMING}

      # Make sure edi temp directory exists and is empty
      if [ ! -d ${TEMP} ]; then
        mkdir ${TEMP}
      else
        rm -rf ${TEMP}/*
      fi

      # Make sure there's a subdirectory for every vendor, to avoid namespace conflicts
      if [ ! -d ${VENDOR} ]; then
        mkdir ${VENDOR}
      fi

      # Could use wget to retrieve only new files from ftp sites
      # Unfortunately, it doesn't work with MVS systems, which several vendors use
      # WGET=/usr/sfw/bin/wget
      # FILEDIR already starts & ends with /
      # ${WGET} -N ftp://${USER}:${PASSWORD}@${MACHINE}${FILEDIR}*

      # For now, use ftp for all retrievals for consistency
      # ftp -n so .netrc won't be used; see comments about .netrc at top of loop
      # 2006-03-23 akohler: not using mdel - too many sites don't allow us to delete
      echo -e "\nGetting EDI files for ${VENDOR}"
      (
        echo "user ${USER} ${PASSWORD}"
        echo "lcd ${TEMP}"
        if [ ${FILEDIR} != "/" ]; then
          echo "cd ${FILEDIR}"
        fi
        echo "bin"
        echo "mget ${FILESPEC}"
        echo "quit"
      ) | ftp -i -n ${MACHINE}

      # Move new files from TEMP to appropriate VENDOR directory, without affecting existing files
      # This preserves dates from original retrieval, which we'll use later to remove old files.
      # For files we already have, compare (vendors do rarely reissue files)
      for FILE in `ls ${TEMP}`; do
        if [ ! -f ${VENDOR}/${FILE} ]; then
          mv ${TEMP}/${FILE} ${VENDOR}
        else
          cmp -s ${TEMP}/${FILE} ${VENDOR}/${FILE}
          RETVAL=$?
          if [ ${RETVAL} -eq 0 ]; then
            # Identical, so discard newly-downloaded file
            rm -f ${TEMP}/${FILE}
          else
            # Same name, different content - unlikely, but output error message
            echo -e "\n*** WARNING: ${VENDOR}/${FILE} exists but new version is different ***\n"
          fi
        fi # TEMP/VENDOR comparison
      done # for FILE in TEMP

      # Voyager client looks only in INCOMING dir, so make symlinks for files 
      # Using hard links because they share timestamp of orig file; soft links don't
      # Voyager can't handle filenames longer than 30 chars, so must shorten some
      YEAR=`date "+%Y"`  #YYYY
      for FILE in `ls ${VENDOR}`; do
        case ${VENDOR} in
          BLA    )
            # BLA filenames don't need first part
            SYMFILE=`echo ${FILE} | awk -F. '{ print $2 "." $3 }'`
            ;;
          COU    )
            # COU reuses filenames; add year to make them unique
            SYMFILE=${FILE}_${YEAR}
            ;;
          EBS    )
            # EBS names for Law are too long; replace acccount-specific first part with LAW_
            SYMFILE=`echo ${FILE} | sed "s/^LA77190.S[0-9][0-9]./LAW_/g"`
            ;;
          HAR    )
            # HAR uses too-long filenames; keep only selected parts
            SYMFILE=`echo ${FILE} | awk -F. '{ print $1 "." $3 "." $4 }'`
            ;;
          MID    )
            # MID uses too-long filenames; keep only selected parts
            SYMFILE=`echo ${FILE} | awk -F. '{ print $2 "." $3 }'`
            ;;
          *      )
            SYMFILE=${FILE}
            ;;
        esac

        # Prepend vendor code to name of symlink
        SYMFILE=${VENDOR}_${SYMFILE}

        # If the file is older than MAXDAYS, remove its symlink, but not the file itself
        #   because FTP doesn't preserve timestamps... so if file is deleted,
        #   but still on FTP site, will wind up as a new file
        # Otherwise (file is newer than MAXDAYS), create the symlink if it doesn't already exist
	#
	# 2006-10-04 akohler: vendors all seem to keep files on their ftp sites for 6 months or less
	#   so now globally deleting EDI invoice files older than 210 days, via vger_daily
        MAXDAYS=30
        ISITOLD=`find ${VENDOR} -name ${FILE} -mtime +${MAXDAYS}`
        if [ -n "${ISITOLD}" ]; then
          if [ -f ${SYMFILE} ]; then
            echo "Removing old file: ${FILE} ${SYMFILE}"
            rm -f ${SYMFILE}
          fi
        else
          # Can test for soft links via -h, but not hard links
          # -f is true for soft and hard links, as well as regular files
          if [ ! -f ${SYMFILE} ]; then
            echo "Adding new file: ${VENDOR}/${FILE} ${SYMFILE}"
            # ln ${VENDOR}/${FILE} ${SYMFILE}
            # 2008-02-05 akohler: Workaround for Voyager bug #19897 (LIN/PIA no ISSN)
            # Run perl script to create fixed copies of EDI files
            # 2008-07-17 akohler: Bug fixed in Voyager 7, no longer need to fix files; back to creating links
            #${EDI}/scripts/fix_edi_pia.pl ${VENDOR}/${FILE} ${SYMFILE}
            ln ${VENDOR}/${FILE} ${SYMFILE}
          fi 
        fi # ISITOLD
      done # for FILE in ls VENDOR
    fi # REQVENDOR / VENDOR
  done # while read
# end of loop
