#!/bin/ksh

# local Voyager env variables
. /opt/local/bin/vger_getenv

# variables to execute java
JAVA=/usr/local/bin/java
JAVADIR=/opt/local/java
PROPFILE=${JAVADIR}/etds.props

DB=ucladb
BASEDIR=/m1/voyager/ucladb/local/cat/etds
READ_BASE=etds_bib
READ_SCHEMA=ucla_preaddb
WRITE_BASE=proc_bib
WRITE_SCHEMA=vger_support

READ_SQL=${BASEDIR}/${READ_BASE}
WRITE_SQL=${BASEDIR}/${WRITE_BASE}
RECORDLIST=${READ_SQL}.out

# setting lang spec to get UTF 8 output
LC_CTYPE=en_US.UTF-8
export LC_CTYPE

# clear out old xml files
rm -f ${BASEDIR}/*.xml

# Get list of record ids
/opt/local/bin/vger_sqlplus_run ${READ_SCHEMA} ${READ_SQL}

while read line
do
  TEMP_FILE=${BASEDIR}/temp.id
  echo ${line} > ${TEMP_FILE}
  BIB_ID=`cut -f 1 -d ':' ${TEMP_FILE}`
  PROQ_ID=`cut -f 2 -d ':' ${TEMP_FILE}`

  ID_FILE=${BASEDIR}/${BIB_ID}.id
  MRC_FILE=${BASEDIR}/${PROQ_ID}.mrc
  XML_FILE=${BASEDIR}/working/${PROQ_ID}.mrc.xml

  echo ${BIB_ID} > ${ID_FILE}

# generate the marc file
  ${VGER_BASE}/${DB}/sbin/Pmarcexport \
    -o${MRC_FILE} \
    -rB \
    -mM \
    -t${ID_FILE} \
    -q

# convert raw marc to xml
  ${JAVA} -cp ${JAVADIR}/marc4j.jar:${JAVADIR}/marcxml.jar gov.loc.marcxml.MARC2MARC21slim ${MRC_FILE} ${XML_FILE}

# retrieve from sftp
  ${JAVA} -jar ${JAVADIR}/etdSftp.jar ${PROPFILE} /${PROQ_ID} ${XML_FILE}

# write the merritt erc metadata file
  ${BASEDIR}/write_erc ${BIB_ID}  

# make zip container for merritt
  ZIP_FILE=${BASEDIR}/${PROQ_ID}.zip
  zip -jqr ${ZIP_FILE} ${BASEDIR}/working/*

# send to merritt
  /opt/local/bin/curl -k -u uclalib:fr9Stucl \
    -F "file=@${ZIP_FILE}" \
    -F "type=container" \
    -F "submitter=uclalib" \
    -F "responseForm=xml" \
    -F "profile=ucla_lib_etd_content" \
    https://merritt.cdlib.org/object/ingest > ${BASEDIR}/${PROQ_ID}.reply.xml

# clean up
  rm -f ${ID_FILE} ${MRC_FILE} ${ZIP_FILE}
  rm -fr ${BASEDIR}/working/*

done <"${RECORDLIST}"

/opt/local/bin/vger_sqlplus_run ${WRITE_SCHEMA} ${WRITE_SQL}
rm -f ${RECORDLIST}

